action_id: trunk-share-with-everyone
date: 2024-06-30 05:53:59
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1719726839
full_timestamp:
  nanos: 476850000
  seconds: 1719726839
trunk_version: 1.22.2
